env:
  browser: true
  commonjs: true
  es6: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  import/no-unresolved: [2, {commonjs: true, amd: true}]
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  no-console: off
  no-underscore-dangle: off
  global-require: off
